version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aungmyomyat874
      - MONGO_INITDB_ROOT_PASSWORD=aungmyomyat874
    ports:
      - "27017:27017"

  my-node-app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=3000
      - DB_HOST=mongodb
      - DB_USER=aungmyomyat874
      - DB_PASSWORD=aungmyomyat874
      - DB_NAME=Blogging
      - DB_PORT=27017
    volumes:
      - ./:/app
# volumes:
#   - ./:/app